### ISSUE TITLE
Cannot install unzip python3, etc

### ISSUE THREAD

**Issue by Magoo356** [Mason10198/SkywarnPlus#106]
ISSUE TEMPLATE
This template is designed to help you report a bug with information required for you to actually be able to receive help. If you choose to ignore this template, do not provide proper files/information with your report, etc., then your issue will be ignored/closed.

**Describe the bug**
When attempting to perform apt install unzip python3 python3-pip ffmpeg on ASL 2.0 beta 6, 
![270515 skywarnplus fail 070524a](https://github.com/Mason10198/SkywarnPlus/assets/174844247/b492beb5-4347-42b6-a819-ad96f8987287)
I get the following errors;
error 404 not found IP:93.93.128.193 80
E: Aborting install
<img width="483" alt="image" src="https://github.com/Mason10198/SkywarnPlus/assets/174844247/003502e2-8512-4661-9378-ed8349e2e26f">

**To Reproduce**
1. Log into ASL 2.0 Beta 6 Raspberry Pi4B-2G node. (32G SD Expanded to full)
2. Start BASH Shell
3. Type apt install unzip python3 python3-pip ffmpeg

**Expected behavior**
I can ping 93.93.128.193 via web browser. I see all the folders. Not sure why the script cannot locate the same IP.
When I go to the ASL "diagnostics" page and pick "show ASL version", it shows GIT a4245fb armv71, Linux 2021-03-24

**Screenshots**
Screen shot attached

**Node (please complete the following information):**
 - OS: ASL BETA 2.0.0 ver 6

**Additional context**
I was successful installing on one node without errors. Same GIT a4245fb version.
Next three nodes, no go. Same error. Cannot find IP.
Interestingly enough, the error shows the IP and then a space between the IP and the port (80). Could that be it?
Now, how do I fix it? 
Thanks for your help!
73 Neil W7FED

**Comment by Mason10198** [comment]
This is going to be an issue with your specific system (network, package sources, repositories, etc) or the Raspbian repository itself.

Closing as this is not an issue with SkywarnPlus.

**Comment by Magoo356** [comment]
Thanks Mason.
It is not my network, package sources, repositories, etc).
Tried 2 different allstar nodes ASL 2.0 Beta 6 on a completely different network, different internet provider, different city.

Same error. 404 Not Found [IP: 93.93.128.193 80]

I have no problems with ASL 3.0

73,
Neil

http://www.qrz.com/db/w7fed

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by Mason10198** [comment]
There is no "script" running here to have an issue with, just some `apt` commands. The `404` error code is in fact a response from the repository server telling you that what you are requesting cannot be found. You are not having network issues, you are having issues with the Raspbian repository telling you that the packages you want are not available. This could still very well be due to improperly configured repositories. ASL 2 was built a long time ago and never made it out of beta - it likely needs manual intervention to make sure the repositories are properly configured. I cannot say for sure because I do not ever use Raspberry Pis. I always use PCs.
