### ISSUE TITLE
Multple Counties

### ISSUE THREAD

**Issue by darinng7o** [Mason10198/SkywarnPlus#108]
I just ran the most recent update everything seems normal except the county names list on Supermon shows the names more then once:

<img width="308" alt="image" src="https://github.com/user-attachments/assets/2b3eb36c-a847-4d75-8453-8724b982a23b">

Any ideas?

**Comment by Mason10198** [comment]
Please do not open new issues without at least providing bare minimum information required for a bug report. The issue template that is prepopulated when creating a new issue explains in detail what is required. Please take the time to read the template rather than simply deleting it.

Closing this until more information is provided.

**Comment by darinng7o** [comment]
I wasn't sure that's why I choose this:

[image: image.png]

Sorry for the intrusion.
