### ISSUE TITLE
NWS text

### ISSUE THREAD

**Issue by darinng7o** [Mason10198/SkywarnPlus#110]
**Is your feature request related to a problem? Please describe.**
It is not related to a problem.

**Describe the solution you'd like**
Is there an option for an end user to "reinstate" the ability to click on an alert instead of the "Skywarnplus Enabled" (see snip)? When this was available before it would take you to the NWS text of the alert.

![image](https://github.com/user-attachments/assets/a83d00c1-dd12-4fea-bece-0e39c4f7c756)

**Describe alternatives you've considered**
No alternatives that I know of using Supermon or Supermon2.

**Additional context**
None

**Comment by Mason10198** [comment]
SkywarnPlus does not support providing a URL to the alert. SkywarnPlus was written specifically to handle checking alerts for several different counties while handling/removing duplicate aletrs.

If there are 3x unique Red Flag Warnings each for Elmore, Ada, and Canyon counties, then how would you choose which of the 9 different URLs to point to when clicking on `Red Flag Warning [Elmore, Ada, Canyon]` on Supermon?

**Comment by darinng7o** [comment]
If I remember correctly the link would take you to the NWS alert then you had to choose the specific alert text you wanted to read.

https://alerts.weather.gov/search?area=ID

**Comment by Mason10198** [comment]
That is correct - this is how the old AUTOSKY used to function. It was easy, because AUTOSKY was unable to handle multiple counties. But the issue still stands for SkywarnPlus...

If there are Red Flag Warnings for Elmore, Ada, and Canyon counties, then how would you choose which of the 3 counties the URL should point to when clicking on `Red Flag Warning [Elmore, Ada, Canyon]` on Supermon?

Again, if you only had one county, this would be super easy. But if you have more than one county, how to you choose where the URL points?

**Comment by darinng7o** [comment]
I seem to remember that autosky did only point to one county. It is possible but it would only work for one county.

Thank you!

**Comment by darinng7o** [comment]
Mason,
I know this is closed, however, can you tell me how I can change this back to the Autosky way? Or at least what file these settings are in?
Thank you!
