### ISSUE TITLE
No crontab entries

### ISSUE THREAD

**Issue by k5map** [Mason10198/SkywarnPlus#124]
I just completed a fresh install of ASL v3 on my SHARI node.  During the install of SWP, I answered "Y" to the questions about creating the crontab jobs.  After completing the installation, when I view the crontab for 'root', there are no entries but the test alerts work.  How is the py script for SWP working without crontab jobs in root?

**Comment by Steve-AG2AA** [comment]
for some reason it ends up in /etc/cron.d/SkywarnPlus

check there. i'm guessing there is a reason but I have no idea what the
reason might be....

**Comment by Mason10198** [comment]
Because there is not just one crontab file. Cron uses everything in the `cron.d` directory in addition to the "user" crontab, which is the one that you are used to making changes to.

It is very common and considered best practice for 3rd party utilities to create their own crontab file to avoid going in and messing around with your own personal crontab file and potentially breaking it.
