### ISSUE TITLE
Say county and state name either before or after warning/watch/statement, etc.

### ISSUE THREAD

**Issue by w4edp** [Mason10198/SkywarnPlus#13]
Say county and state name either before or after warning/watch/statement, etc.

Example: "Special Weather Statement, Walker County Georgia".

I live where 3 states come together and within my repeaters are 3 states, 8 counties and 2 time zones.  Some of my repeaters cover more than 1 county or 1 state.

**Comment by Mason10198** [comment]
This would be difficult, as it would require SWP to know the names of the counties, keep track of which counties each alert came from, among other things... I'm not sure it would be a good idea to implement this even if it were easy -

SWP removes duplicate alerts automatically, so if you are watching 5 different counties that all have the same `Special Weather Statement`, you don't end up hearing `Special Weather Statement` 5 times in a row. Thus, if your alert broadcast were to speak "Special Weather Statement, Walker County Georgia", it could very well be massive misinformation as the same alert actually exists in your other 4 counties as well.

You could get around this by adding the name of ALL counties affected to the end of each alert, but then you end up with alerts and tailmessages that are way too long for a system intended for two-way traffic.

Instead of persuing this, I would suggest making use of the new `SkyDescribe` feature, which can be executed manually or automatically to generate and broadcast on-demand full descriptions of weather alerts whenever necessary. The alert descriptions from the NWS will contain detailed information on the areas affected by the alert.

**Comment by w4edp** [comment]
Is there an option in SWP to play a sound file after an alert?  If so I could do the following (as an example):  I have a repeater located in the NW corner of GA that has coverage in GA, AL and TN.  Since the repeater is physically in GA, I base SWP on that and have a sound file that "tails" SWP that says "Walker County, Georgia".

**Comment by Mason10198** [comment]
Done! :) Ability to add custom audio files to end of alert audio or tailmessage audio implemented in `v0.2.5`

**Comment by w4edp** [comment]
Thank You!

To put some perspective behind my request...  I have multiple repeaters that sit where TN, AL and GA state lines come together.  These repeaters cover 3 states, 11 counties and 2 time zones.  While I'm sure I'm not the only one that deals with this scenario, I need to make sure that when one of these repeaters broadcasts a weather alert of any kind. that listeners know what state/county that alert pertains to.

**Comment by Mason10198** [comment]
User definable "County Identifiers" implemented in `v0.4.0` (say county name after watch/warning/statement/etc)
