### ISSUE TITLE
problem with Inject Files not working

### ISSUE THREAD

**Issue by Bradn8pc** [Mason10198/SkywarnPlus#51]
after update to 4.2  when you go into the config.yaml and set cleanslate to true and Inject files to true for testing then run ./SkyWarnPlus.py it does not run the Inject, it just runs as if normal

 # Delete cached data on startup
  CLEANSLATE: true

  # Specify the TMP directory.
  TmpDir: /tmp/SkywarnPlus

  # Write alert titles to /tmp/AUTOSKY/warnings.txt for Supermon backwards compatibility.
  SupermonCompat: true

  # Enable test alert injection instead of calling the NWS API by setting 'INJECT' to 'True'.
  INJECT: true
  
this is what is set and then when I run it this happens

[root@N8PC_Repeater SkywarnPlus]# ./SkywarnPlus.py
2023-07-31 22:07:01,287 INFO No change in alerts.
2023-07-31 22:07:01,287 INFO Current alerts: None.

it is acting as if it is not even running it at all

**Comment by Bradn8pc** [comment]
Update: I manually deleted the directory /usr/local/bin/SkywarnPlus  and then reinstalled with the instructions to have a full copy in place and now all works as it should. 

is there anyway to announce the County at the beginning instead of the end of each alert. Like hancock county then annouce all for that county then move to the next county?

**Comment by Mason10198** [comment]
The reason that alert injection did not work until after you reinstalled is because the test alerts in your `config.yaml` were not updated to the new v0.4.0 format. This is a manual process that the update script cannot do for you. Check the release notes for more information.

When you reinstalled, you rebuilt the YAML from scratch with the default template, which has the test alerts in the correct format.

There is not currently a way to change the placement of the county identifier tags, they will always be after the alerts. You can submit a feature request if this is something you'd like to see added.
