### ISSUE TITLE
Is this normal?

### ISSUE THREAD

**Issue by w8cpt** [Mason10198/SkywarnPlus#66]
**Describe the bug**
In my log I get
 " WARNING[17679] file.c: Unable to open /tmp/SkywarnPlus/wx-tail (format 0x4 (ulaw)): No such file or directory"

**Node (please complete the following information):**
  HAMVOIP 1.7 on a Pi3 A+

**Additional context**
This could be because there's no current alert or warning if so sorry just confirming! My node keeps dropping while receiving a transmission from someone else for like 2 seconds then beeps and comes back. I doubt this is the issue but checking everything! Thanks!

**Comment by Mason10198** [comment]
The error you provided is from the Asterisk console log. This message indicates that Asterisk is attempting to play an audio file, but the specified audio file is not available.

It is likely that you have configured your `rpt.conf` file for SkywarnPlus Tailmessages per the README. Please ensure that you have also properly configured the SkywarnPlus `config.yaml` file correctly for Tailmessages to be generated. If there are no alerts, then the Tailmessage file should be a short 0.10 second burst of silence - meaning the file should still exist, and just be empty. This prevents the error message.

Since you are getting the error, I suspect that you have something configured incorrectly that Asterisk is looking for a valid Tailmessage file but cannot find it.

The error message is not harmful and can be ignored. It will not cause any issues on your system. It just means "hey you asked me to play this file, but I can't".

**Comment by w8cpt** [comment]
Ok I updated SkywarnPlus and double checked all the settings. I think it
possibly is saying "there's no warnings etc so nothing to announce"....
