### ISSUE TITLE
Supermon/Supermon2 Integration

### ISSUE THREAD

**Issue by k5dvt** [Mason10198/SkywarnPlus#71]
It would be cool if in Allmon/Supermon/Supermon2 the alerts were shown on a scroller on the page, or maybe just statically shown below the node list table. It would also be cool if the back ground changed colors/pictures on alerts to give users a heads up that "hey there's a weather alert."

**Comment by Mason10198** [comment]
It's a good idea, but ultimately this is entirely up to the developers behind those frontends to process and display the data from SkywarnPlus. SkywarnPlus can provide data, but cannot change how those frontends operate.

For example, Supermon contains a function to read the alerts.txt file created by AutoSkywarn, so I was able to have SkywarnPlus create a similarly formatted alerts.txt in order to make Supermon backwards compatible, but changing how that data is processed and displayed requires modification to Supermon, not SkywarnPlus.
